# Generated by Django 5.2.4 on 2025-07-16 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libro',
            new_name='Juegos',
        ),
    ]
