# Generated by Django 5.2.4 on 2025-07-17 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_libro_juegos'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='juegos/'),
        ),
    ]
