# Generated by Django 5.2.4 on 2025-07-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_juegos_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='es_reseña',
            field=models.BooleanField(default=False),
        ),
    ]
