# Generated by Django 5.2.4 on 2025-08-17 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_juegos_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='juegos',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='juegos',
            name='imagen',
            field=models.ImageField(blank=True, default='img/img_post_default.jpg', null=True, upload_to='libros'),
        ),
    ]
