# Generated by Django 5.2.4 on 2025-08-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='imagen',
            field=models.ImageField(blank=True, default='img/default.png', null=True, upload_to='usuarios/'),
        ),
    ]
