# Generated by Django 5.2.4 on 2025-08-12 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_alter_juegos_autor'),
        ('login', '0002_alter_perfilusuario_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.juegos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
